name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_svg: 
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.1.0
  google_fonts: ^4.0.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/images/
  - assets/icons/
  - assets/fonts/
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltBlack.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltBlackItalic.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltBold.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltBoldItalic.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraBold.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraBoldItalic.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraLight.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraLightItalic.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltHeavy.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltHeavyItalic.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueRegular.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueMedium.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraLight.otf
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueAltExtraLight.otf
